# Generated by Django 3.0.4 on 2020-03-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
