# Generated by Django 3.0.4 on 2020-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200327_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='This user has no written a bio.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.TextField(default='https://cdn3.iconfinder.com/data/icons/avatars-9/145/Avatar_Alien-512.png'),
        ),
    ]
